### ISSUE TITLE
2023/12/15 五大联赛

### ISSUE THREAD

**Issue by lottery10086** [czl0325/football_frontend#2]
%12/15 22：01更新
精力有限，只看了五大联赛的几场比赛的预测数据
数据是基于12/15 21：50的盘口进行预测的

#1 德甲
![d5dd556fd04f6ad72cb7f1005b58326](https://github.com/czl0325/football_frontend/assets/153923418/4fc9a11a-6ebd-4c63-9f0b-3cbbcb51da1a)

#2 意甲
**尤文不败/进球数1+2**
![d8fc9fcad5b633bae7dbfb9115f5116](https://github.com/czl0325/football_frontend/assets/153923418/e6ef9c49-3d0a-43a0-8571-e95921f4ebb6)

#3 英超
![ed3041cf32317f0ec997573759b8f77](https://github.com/czl0325/football_frontend/assets/153923418/1bed4a2f-d169-4f94-85f2-7480ea2c89cf)

#4  西甲
**奥萨苏纳平负**
![4a3d177c09ec86bae85aa8237af6c50](https://github.com/czl0325/football_frontend/assets/153923418/7f66343a-d2c1-4f69-9879-2d360395b92a)

#5 法甲
![ec6159546d16feb9bacdf00cd404b85](https://github.com/czl0325/football_frontend/assets/153923418/0d6ef778-08f9-42ce-96d8-266b3bebbdfe)

感谢大佬，静待明早收米！！！

**Comment by lottery10086** [comment]
开奖啦

#1 德甲
门兴2-2不来梅    【**比分概率预测正确**】

#2 意甲
热那亚1-1尤文    【**尤文不败/进球数2/比分概率正确**】

#3英超
诺丁汉0-2热刺

#4西甲
奥萨苏纳1-0巴列卡诺    【**_奥萨苏纳平负 错误_**】

#5法甲
摩纳哥0-1马赛

**Comment by czl0325** [comment]
你这是竞彩，我这算法不适合竞彩，我是对比开盘的初赔和最终定格的终赔来匹配。你竞彩购买结束时间离比赛开始时间还那么早，后面的变化导致预测结果不准确，你要从复盘板块进去找到这场比赛，看看最终的预测结果是什么样的。
还有你这个数据也不算好，全网概率要高于6成，本联赛概率高于7成，这样的数据才算好。55%的概率不值得打
