### ISSUE TITLE
为什么我搭建完后无法加载比赛列表？？？

### ISSUE THREAD

**Issue by taohe009** [czl0325/football_frontend#4]
![微信图片_20240113211304](https://github.com/czl0325/football_frontend/assets/128437219/f18d3ae3-099a-40e6-ad8b-a0ec62441987)

如图所示

**Comment by czl0325** [comment]
开发环境访问我本地的，要改成线上环境

**Comment by taohe009** [comment]
怎么改呀，请指教，还是说你的数据库在你本地呢？我访问不了？
